### ISSUE TITLE
jqtree.css did not support IE7, IE8

### ISSUE THREAD

**Issue by gsmlg** [mbraak/jqTree#342]
```css
ul.jqtree-tree li.jqtree-selected > .jqtree-element,
ul.jqtree-tree li.jqtree-selected > .jqtree-element:hover {
    background-color: #97BDD6;
    background: -webkit-gradient(linear, left top, left bottom, from(#BEE0F5), to(#89AFCA));
    background: -moz-linear-gradient(top, #BEE0F5, #89AFCA);
    background: -ms-linear-gradient(top, #BEE0F5, #89AFCA);
    background: -o-linear-gradient(top, #BEE0F5, #89AFCA);
    text-shadow: 0 1px 0 rgba(255, 255, 255, 0.7);
}
```
should be this:
```css
ul.jqtree-tree li.jqtree-selected > .jqtree-element,
ul.jqtree-tree li.jqtree-selected > .jqtree-element:hover {
    background-color: #97BDD6;
    background-image: -webkit-gradient(linear, left top, left bottom, from(#BEE0F5), to(#89AFCA));
    background-image: -moz-linear-gradient(top, #BEE0F5, #89AFCA);
    background-image: -ms-linear-gradient(top, #BEE0F5, #89AFCA);
    background-image: -o-linear-gradient(top, #BEE0F5, #89AFCA);
    text-shadow: 0 1px 0 rgba(255, 255, 255, 0.7);
}
```
