### ISSUE TITLE
CSS can't change backgound color for selected element on hover

### ISSUE THREAD

**Issue by Chocapic** [mbraak/jqTree#344]
I've added : 

```css
.jqtree-element:hover{
    background-color:#959595;
}
```
to the css which works fine however the background color wont change when I hover selected elements. How to achieve this ? 

Thanks

**Comment by mbraak** [comment]
I think you have to add the ``jqtree-selected`` css selector. You also have to clear the background:

```css
.jqtree-element:hover,
ul.jqtree-tree li.jqtree-selected > .jqtree-element:hover {
    background-color:#959595;
    background: none;
}
```
