### ISSUE TITLE
css style for increasing the node spacing

### ISSUE THREAD

**Issue by sribat** [mbraak/jqTree#358]
Hi, I just started exploring your plugin and it seems very apt for our application. We need more spacing between nodes of the tree. Can you please guide me how to implement this. Thanks!

**Comment by mbraak** [comment]
You can style the tree using css. So you could do something like this:

```css
ul.jqtree-tree .jqtree-element {
    margin: 8px 0;
}
```
