### ISSUE TITLE
autoscroll issue

### ISSUE THREAD

**Issue by hbaptiste** [mbraak/jqTree#402]
For some reasons the autoscroll feature when I drag a node won't work on my project.
As I don't have any error message, I would like to ask you what can prevent it from working.
The dragged node is way out of its container but the scrollbar stays still.
Thanks for your help. And for jqTree.

**Comment by mbraak** [comment]
Please have a look at the [autoscroll example](https://mbraak.github.io/jqTree/examples/07_autoscroll.html). Perhaps your code is different.

```html
<div id="scroll-container">
    <div id="tree1"></div>
</div>
```

The css:
```css
#scroll-container {
    height: 200px;
    overflow-y: scroll;
    position: relative;  /* ie7 fix */
    -ms-user-select: none;
    user-select: none;
}
```

**Comment by hbaptiste** [comment]
Thanks for your help. Unfortunately for me, I have the same structure and the same css as your example.

**Comment by mbraak** [comment]
Hmm that's strange. Perhaps some other css on your page is interfering?

**Comment by hbaptiste** [comment]
After some tests, I think it appends when we render the tree in an element (documentFragment) and then appends that element to the dom. Is there a way to refresh the tree's dimension after it has been rendered?
Thanks again for your help.

**Comment by mbraak** [comment]
It could be a problem if you change the parent of the tree.

Could you share some code? Then I can try to reproduce the bug.

**Comment by hbaptiste** [comment]
Here is my code to reproduce the bug.
```
var treeviewWrapper = jQuery("<div id='treeview-wrapper', class='treeview-ctn'>");
                treeviewWrapper.append("<div id='core-tree'/>");

                treeviewWrapper.css({
                    height: "200px",
                    width: "250px",
                    position:'absolute',
                    top: '200px',
                    left: '400px',
                    border: '1px solid green',
                    backgroundColor: 'white',
                    overflowY: 'scroll'
                });
```

````
jQuery(treeviewWrapper).find("#core-tree").tree({dragAndDrop:true, data: DataExample.example_data, autoOpen: false});

               setTimeout(function () {
                   jQuery('body').append(treeviewWrapper);
               }, 5000);
````

**Comment by mbraak** [comment]
I think the problem is that the wrapper element has `position: absolute`.

Perhaps you can wrap the `treeview-wrapper` in another container:

```
<div id="treeview-abs">
  <div id="treeview-wrapper">
    <div id="core-tree" />
  </div>
</div>
```

css:

```css
#treeview-abs {
  height: 200px,
  width: 250px,
  position: absolute,
  top: 200px,
  left: 400px,
}

#treeview-wrapper {
  position: relative;
  overflowY: scroll;
}
```
