### ISSUE TITLE
Selected Node Problem

### ISSUE THREAD

**Issue by SammyDz** [mbraak/jqTree#699]
The selected node is showing a border around the text.  (See image)
How do I get rid of the border?  The css doesn't seem to have a way to do that.

![jqTreeIssue](https://user-images.githubusercontent.com/26631781/205087398-5698247d-f758-4557-9acc-2d49a50af071.png)

**Comment by mbraak** [comment]
The following css works in my demo app:

```css
.jqtree-title:focus {
    outline: 0;
}
```
